name: Tests

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0 #for better blame info
    - name: Download vendored dependencies
      run: go mod vendor
    - name: Tests and coverage
      run: go test -v -coverpkg=./... -coverprofile=coverage-coraza-caddy.out ./...   
#    - name: SonarCloud Scan
#      uses: sonarsource/sonarcloud-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      